# .github/workflows/daily-twitter-report.yml
# ------------------------------------------------------------
# Runs the DAILY Twitter analytics report
# ------------------------------------------------------------

name: Daily Twitter Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 03:00 UTC

jobs:
  build-run:
    runs-on: ubuntu-latest

    env:
      # ---------- Supabase ----------
      SUPABASE_HOST:         ${{ secrets.SUPABASE_HOST }}
      SUPABASE_PORT:         ${{ secrets.SUPABASE_PORT }}
      SUPABASE_DB:           ${{ secrets.SUPABASE_DB }}
      SUPABASE_USER:         ${{ secrets.SUPABASE_USER }}
      SUPABASE_PWD:          ${{ secrets.SUPABASE_PWD }}
      SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      SB_BUCKET:             ${{ vars.SB_BUCKET || 'daily-reports' }}

      # ---------- OpenAI ----------
      OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}

      # ---------- Mailjet ----------
      MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}
      MAIL_FROM:             ${{ vars.MAIL_FROM }}
      MAIL_TO:               ${{ vars.MAIL_TO }}

      CI: true
      R_KEEP_PKG_SOURCE: no

    steps:
      # 1) Source code
      - uses: actions/checkout@v4

      # 2) R + pandoc
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2

      # 3) Headless Chrome for pagedown PDF rendering
      - name: Install headless Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          chrome-version: stable

      # 3-b) Expose the path so R / pagedown can find it   ⟵  NEW
      - run: echo "CHROME_BIN=$CHROME_PATH" >> "$GITHUB_ENV"


      # 4) System libraries for R packages
      - name: Install system libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1 libharfbuzz-dev libfribidi-dev \
            libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      # 5) Install R package dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::lubridate
            any::httr2
            any::httr
            any::jsonlite
            any::glue
            any::pagedown
            any::RPostgres
            any::DBI
            any::base64enc
            any::tidytext

      # 6) (Optional) Debug pagedown Chrome path
      - name: Debug Chrome path
        run: |
          echo "CHROME_BIN -> $CHROME_BIN"
          Rscript -e 'cat("pagedown::find_chrome() ->", pagedown::find_chrome(), "\n")'

      # 7) Run the R script
      - name: Run generate_report.R
        run: Rscript generate_report.R

      # 8) Save local artefacts (e.g., for manual debugging)
      - name: Upload report artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-report-artifacts
          path: |
            summary.md
            summary_full.pdf
          if-no-files-found: warn
