# .github/workflows/daily-twitter-report.yml
# ------------------------------------------------------------
# Runs the DAILY Twitter “Launches & Activities” report
# ------------------------------------------------------------

name: Daily Twitter Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"       # every day @ 03:00 UTC

jobs:
  build-run:
    runs-on: ubuntu-latest

    # ── env vars / secrets ────────────────────────────────────
    env:
      ## Supabase
      SUPABASE_HOST:         ${{ secrets.SUPABASE_HOST }}
      SUPABASE_PORT:         ${{ secrets.SUPABASE_PORT }}
      SUPABASE_DB:           ${{ secrets.SUPABASE_DB }}
      SUPABASE_USER:         ${{ secrets.SUPABASE_USER }}
      SUPABASE_PWD:          ${{ secrets.SUPABASE_PWD }}
      SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      SB_BUCKET:             ${{ vars.SB_BUCKET || 'daily-reports' }}

      ## OpenAI
      OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}

      ## Mailjet
      MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}
      MAIL_FROM:             ${{ vars.MAIL_FROM }}
      MAIL_TO:               ${{ vars.MAIL_TO }}

      ## tidy-CI defaults
      CI: true
      R_KEEP_PKG_SOURCE: no

    steps:
      # 1 · source code
      - uses: actions/checkout@v4

      # 2 · R + pandoc (Posit binary cache for faster installs)
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2

      # 3 · install headless Chrome (needed by pagedown)
      #     keep the step id so we can read its output later
      - name: Install headless Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          chrome-version: stable            # or pin a specific version

      # 4 · Linux system libraries many CRAN pkgs need
      - name: Install Linux libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1-dev libharfbuzz-dev libfribidi-dev \
            libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      # 5 · resolve & cache R package deps
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::lubridate
            any::httr2
            any::httr
            any::jsonlite
            any::glue
            any::pagedown
            any::RPostgres
            any::DBI
            any::base64enc
            any::tidytext

      # 6 · run the report-generation script
      - name: Run generate_report.R
        run: Rscript generate_report.R
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}   # ← pass path

      # 7 · upload artefacts (helpful for debugging)
      - name: Upload report artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-report-artifacts
          path: |
            summary.md
            summary_full.pdf
          if-no-files-found: warn

